[workspace]
authors = ["Andrew Suprun <andrew.suprun@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "Game-Of-Stones"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.4.0.dev2025061222,<26"
pygame = ">=2.6.1,<3"
