[workspace]
authors = ["Andrew Suprun <andrew.suprun@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "Game-Of-Stones"
platforms = ["osx-arm64"]
version = "1.0.0"

[tasks]
c6-mcts = "mojo run -I src apps/connect6_mcts.mojo"
c6-negamax = "mojo run -I src apps/connect6_negamax.mojo"
c6-sim = "mojo run -I src apps/sim_connect6.mojo"
gomoku-mcts = "mojo run -I src apps/gomoku_mcts.mojo"
gomoku-negamax = "mojo run -I src apps/gomoku_negamax.mojo"
gomoku-sim = "mojo run -I src apps/sim_gomoku.mojo"
eval-board = "mojo run -I src -D ASSERT=all apps/eval_board.mojo"
test = "mojo test -I src -D ASSERT=all test"
benches = "benches/run.sh"
format = "pixi run mojo format src test benches apps -l 180"

[dependencies]
pygame = ">=2.6.1,<3"
mojo = "25.5.*"
