[workspace]
authors = ["Andrew Suprun <andrew.suprun@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "Game-Of-Stones"
platforms = ["osx-arm64"]
version = "1.0.0"

[tasks]
c6-sim = "mojo run -I src -D ASSERT=all apps/sim_connect6.mojo"
negamax-sim = "mojo run -I src -D ASSERT=all apps/sim_negamax_connect6.mojo"
gomoku-sim = "mojo run -I src -D ASSERT=all apps/sim_gomoku.mojo"
eval-board = "mojo run -I src -D ASSERT=all apps/eval_board.mojo"
benches = "benches/run.sh"
format = "pixi run mojo format src test benches apps -l 180"

[dependencies]
pygame = ">=2.6.1,<3"
mojo = ">=0.26.2.0.dev2026022505,<0.27"
